language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=InlineCss
    - REQUIRE=""

matrix:
  include:
    - php: 5.4
      env:
        - PHPCS=1
  allow_failures:
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - echo "require APP . 'vendor' . DS . 'autoload.php';" >> ../cakephp/app/Config/bootstrap.php

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
